### ISSUE TITLE
Incorrect forecast horizon in model image

### ISSUE THREAD

**Issue by shaido987** [LongxingTan/KDDCup2022-WPF#1]
Hello @LongxingTan,

Very interesting work, I look forward to reading the detailed report. 

When looking at the model overview in the image here on github, at the output layer you have T=t+x+299. I assume that this should be 288? Also, the readme says 4th place while the about section writes 3rd place.

**Comment by LongxingTan** [comment]
Thanks so much for the reminder.

- yeah, 299 is a typo. 
- I was informed that I'm 3rd place, while I was ended in 4th in leaderboard. So, I think I could update the readme to 3rd place solution now :)

**Comment by shaido987** [comment]
No problems. I think so, we also went from 7th to 6th place. 😄
